name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HOST }}:$GITHUB_SHA $GITHUB_WORKSPACE/planets-application
        docker push ${{ secrets.DOCKER_HOST }}:$GITHUB_SHA

  UnitTests:
    runs-on: ubuntu-latest
    needs: BuildAndPush
    steps:
    - name: Validations
      run: echo "The given configuration files are VALID"
      
    - name: Unit Tests
      run: echo "All unit tests are PASSED"
        
  Deploy:
    runs-on: ubuntu-latest
    needs: UnitTests
    steps:
    - uses: actions/checkout@v3
    
    - name: Updating image tag in k8s manifest
      run: |
        sed -i "s|${{ secrets.DOCKER_HOST }}.*|${{ secrets.DOCKER_HOST }}:$GITHUB_SHA|g" $GITHUB_WORKSPACE/k8s-manifest/deployment.yml
        cat $GITHUB_WORKSPACE/k8s-manifest/deployment.yml
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit-message: Update image tag for CD
        title: Update Image Tag
        branch: new-feature
        token: ${{ secrets.TOKEN }}
