apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:f0566c7e459417c0696ef7a03496e44932effc2e
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
