apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:d2d83670c962d953617d69a35f93da51ce736280
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
