apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:706d825f217e43b2b99bc74b7ad06f03b859a0a2
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
