apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:ee44f6ee9d966014616f11a494ef3fc678d28e57
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
