apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:dc31350b1569ca74a0fa7e2962158d6d4c77a87f
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
