apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:906088233946ce44d24dbc3fc757f77b21f5e407
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
