apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:88599749c5e26b78bf24d5a97dbf3670b47d8603
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
