apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:6779928490329b7504bd348c050880a9362ce45a
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
