apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:fc6e3be46c30556cda4047fc724eb4a790f55e45
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
