apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: faizan1419/planets-demo:72a92e1e812abb9725953c5ed70e8431fe712bba
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
